baseURL = "https://ffajardo64.github.io/statistical_learning/"
languageCode = "pt-br"
title = "Statistical Learning"
# Theme
theme = "hugo-theme-cleanwhite"
# Params
enableEmoji = true
enableRobotsTXT = true
enableMissingTranslationPlaceholders = true
#googleAnalytics = "UA-143083330-1"

[params]
title = "GopheRio - Golang meetup no Rio de Janeiro"
date = "2019-10-03"
description = "O GopheRio é uma comunidade de usuários Golang no Rio de Janeiro"
images = ["/images/social-share.jpg"]
email = "gopheriomeetup@gmail.com"
keywords = "event, google, programming, go, golang, developers, web, cloud"
copyright = "Fabio Fajardo"
cfpUrl = "https://forms.gle/YhqM93oHFXDLn2K48"
subscriptionUrl = "http://meetup.com/gopherio"
appleTouchIcon = "/apple-touch-icon.png"
favicon32 = "/favicon-32x32.png"
favicon16 = "/favicon-16x16.png"
manifest = "/manifest.json"
safariPinnedTab = "/safari-pinned-tab.svg"
themeColor = "#673ab7"

[params.logos]
jumbo = "/themes/hugo-theme-cleanwhite/images/logos/devfest_color_text.png"
header = "/themes/hugo-theme-cleanwhite/images/logos/devfest_color_text.png"
footer = "/themes/hugo-theme-cleanwhite/images/logos/devfest_gray_text.png"

[menu]
[[menu.main]]
identifier = "meetup"
name = "Meetup"
url = "https://ffajardo64.github.io/statistical_learning/"
weight = 200
external = true
